---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-resources-wazuh-com-v1-wazuhcluster
  failurePolicy: Fail
  name: mwazuhcluster.kb.io
  rules:
  - apiGroups:
    - resources.wazuh.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - wazuhclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-resources-wazuh-com-v1-opensearchauthconfig
  failurePolicy: Fail
  name: vopensearchauthconfig.kb.io
  rules:
  - apiGroups:
    - resources.wazuh.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - opensearchauthconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-resources-wazuh-com-v1-wazuhcluster
  failurePolicy: Fail
  name: vwazuhcluster.kb.io
  rules:
  - apiGroups:
    - resources.wazuh.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - wazuhclusters
  sideEffects: None
