/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package security

import (
	"context"
	"crypto/sha256"
	"fmt"
	"sort"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/tools/record"
	"sigs.k8s.io/controller-runtime/pkg/client"

	wazuhv1 "github.com/MaximeWewer/wazuh-operator/api/v1"
	"github.com/MaximeWewer/wazuh-operator/pkg/constants"
)

// CredentialManager manages OpenSearch admin credentials
type CredentialManager struct {
	k8sClient client.Client
	recorder  record.EventRecorder
}

// NewCredentialManager creates a new CredentialManager
func NewCredentialManager(k8sClient client.Client, recorder record.EventRecorder) *CredentialManager {
	return &CredentialManager{
		k8sClient: k8sClient,
		recorder:  recorder,
	}
}

// AdminCredentials holds the resolved admin credentials
type AdminCredentials struct {
	Username string
	Password string
	Source   string // "auto" or "crd"
	CRDName  string // Name of the CRD if source is "crd"
}

// GetAdminCredentials returns the admin username and password for a cluster
// It checks for CRD-defined admin first, falls back to auto-generated
func (c *CredentialManager) GetAdminCredentials(ctx context.Context, cluster *wazuhv1.WazuhCluster) (*AdminCredentials, error) {
	// Try to find a CRD-defined admin first
	adminUser, err := c.ResolveDefaultAdmin(ctx, cluster)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve default admin: %w", err)
	}

	if adminUser != nil {
		// Get credentials from CRD
		password, err := c.GetPasswordFromCRD(ctx, adminUser)
		if err != nil {
			return nil, fmt.Errorf("failed to get password from CRD %s: %w", adminUser.Name, err)
		}

		return &AdminCredentials{
			Username: adminUser.Name,
			Password: password,
			Source:   wazuhv1.SecuritySourceCRD,
			CRDName:  adminUser.Name,
		}, nil
	}

	// Fall back to auto-generated credentials from the secret
	username, password, err := c.getAutoGeneratedCredentials(ctx, cluster)
	if err != nil {
		return nil, fmt.Errorf("failed to get auto-generated credentials: %w", err)
	}

	return &AdminCredentials{
		Username: username,
		Password: password,
		Source:   wazuhv1.SecuritySourceAuto,
	}, nil
}

// FindDefaultAdminCRDs finds all OpenSearchUser CRDs marked as defaultAdmin for a cluster
func (c *CredentialManager) FindDefaultAdminCRDs(ctx context.Context, clusterRef types.NamespacedName) ([]wazuhv1.OpenSearchUser, error) {
	// List all OpenSearchUser CRDs in the namespace
	var userList wazuhv1.OpenSearchUserList
	if err := c.k8sClient.List(ctx, &userList, client.InNamespace(clusterRef.Namespace)); err != nil {
		return nil, fmt.Errorf("failed to list OpenSearchUser CRDs: %w", err)
	}

	// Filter for defaultAdmin users that reference this cluster
	var defaultAdmins []wazuhv1.OpenSearchUser
	for _, user := range userList.Items {
		if user.Spec.DefaultAdmin && user.Spec.ClusterRef.Name == clusterRef.Name {
			defaultAdmins = append(defaultAdmins, user)
		}
	}

	// Sort by creation timestamp (oldest first)
	sort.Slice(defaultAdmins, func(i, j int) bool {
		return defaultAdmins[i].CreationTimestamp.Before(&defaultAdmins[j].CreationTimestamp)
	})

	return defaultAdmins, nil
}

// ResolveDefaultAdmin selects the admin user and emits warnings if conflicts
func (c *CredentialManager) ResolveDefaultAdmin(ctx context.Context, cluster *wazuhv1.WazuhCluster) (*wazuhv1.OpenSearchUser, error) {
	clusterRef := types.NamespacedName{
		Name:      cluster.Name,
		Namespace: cluster.Namespace,
	}

	defaultAdmins, err := c.FindDefaultAdminCRDs(ctx, clusterRef)
	if err != nil {
		return nil, err
	}

	if len(defaultAdmins) == 0 {
		// No CRD-defined admin, use auto-generated
		return nil, nil
	}

	// Use the first one (oldest by creation timestamp)
	selectedAdmin := &defaultAdmins[0]

	// Emit warnings for additional default admins
	for i := 1; i < len(defaultAdmins); i++ {
		extraAdmin := &defaultAdmins[i]
		if c.recorder != nil {
			c.recorder.Eventf(extraAdmin, corev1.EventTypeWarning, "MultipleDefaultAdmin",
				"Multiple users marked as defaultAdmin for cluster %s. Using %s instead of %s",
				cluster.Name, selectedAdmin.Name, extraAdmin.Name)
		}
	}

	return selectedAdmin, nil
}

// GetPasswordFromCRD retrieves the password for an OpenSearchUser CRD
func (c *CredentialManager) GetPasswordFromCRD(ctx context.Context, user *wazuhv1.OpenSearchUser) (string, error) {
	// If a hash is provided directly, we can't retrieve the password
	// This is only valid for syncing to OpenSearch, not for authentication
	if user.Spec.Hash != "" && user.Spec.PasswordSecret == nil {
		return "", fmt.Errorf("user %s only has a hash, no password available for authentication", user.Name)
	}

	// Get password from secret
	if user.Spec.PasswordSecret == nil {
		return "", fmt.Errorf("user %s has no passwordSecret configured", user.Name)
	}

	secretKey := types.NamespacedName{
		Name:      user.Spec.PasswordSecret.SecretName,
		Namespace: user.Namespace,
	}

	var secret corev1.Secret
	if err := c.k8sClient.Get(ctx, secretKey, &secret); err != nil {
		return "", fmt.Errorf("failed to get password secret %s: %w", user.Spec.PasswordSecret.SecretName, err)
	}

	// Use PasswordKey from CredentialsSecretRef (default to "password")
	key := user.Spec.PasswordSecret.PasswordKey
	if key == "" {
		key = "password"
	}

	passwordBytes, ok := secret.Data[key]
	if !ok {
		return "", fmt.Errorf("key %s not found in secret %s", key, user.Spec.PasswordSecret.SecretName)
	}

	return string(passwordBytes), nil
}

// getAutoGeneratedCredentials retrieves the auto-generated credentials from the indexer-credentials secret
func (c *CredentialManager) getAutoGeneratedCredentials(ctx context.Context, cluster *wazuhv1.WazuhCluster) (username, password string, err error) {
	secretName := constants.IndexerCredentialsName(cluster.Name)
	secretKey := types.NamespacedName{
		Name:      secretName,
		Namespace: cluster.Namespace,
	}

	var secret corev1.Secret
	if err := c.k8sClient.Get(ctx, secretKey, &secret); err != nil {
		return "", "", fmt.Errorf("failed to get credentials secret %s: %w", secretName, err)
	}

	usernameBytes, ok := secret.Data[constants.SecretKeyAdminUsername]
	if !ok {
		return "", "", fmt.Errorf("%s not found in secret %s", constants.SecretKeyAdminUsername, secretName)
	}

	passwordBytes, ok := secret.Data[constants.SecretKeyAdminPassword]
	if !ok {
		return "", "", fmt.Errorf("%s not found in secret %s", constants.SecretKeyAdminPassword, secretName)
	}

	return string(usernameBytes), string(passwordBytes), nil
}

// ComputeCredentialsHash computes a hash of the credentials for change detection
func (c *CredentialManager) ComputeCredentialsHash(ctx context.Context, cluster *wazuhv1.WazuhCluster) (string, error) {
	creds, err := c.GetAdminCredentials(ctx, cluster)
	if err != nil {
		return "", err
	}

	// Compute SHA256 of username + password
	data := fmt.Sprintf("%s:%s", creds.Username, creds.Password)
	hash := sha256.Sum256([]byte(data))
	return fmt.Sprintf("%x", hash[:8]), nil // Use first 8 bytes for a shorter hash
}

// PropagateCredentials updates dashboard and manager with current credentials
// This is done by updating an annotation to trigger rolling updates
func (c *CredentialManager) PropagateCredentials(ctx context.Context, cluster *wazuhv1.WazuhCluster) error {
	// Get current credentials hash
	hash, err := c.ComputeCredentialsHash(ctx, cluster)
	if err != nil {
		return fmt.Errorf("failed to compute credentials hash: %w", err)
	}

	// Update dashboard deployment annotation
	dashboardName := constants.DashboardName(cluster.Name)
	if err := c.updateDeploymentAnnotation(ctx, cluster.Namespace, dashboardName, hash); err != nil {
		return fmt.Errorf("failed to update dashboard annotation: %w", err)
	}

	// Update manager StatefulSet annotation (master)
	masterName := constants.ManagerMasterName(cluster.Name)
	if err := c.updateStatefulSetAnnotation(ctx, cluster.Namespace, masterName, hash); err != nil {
		return fmt.Errorf("failed to update manager-master annotation: %w", err)
	}

	// Update manager StatefulSet annotation (workers)
	workersName := constants.ManagerWorkersName(cluster.Name)
	if err := c.updateStatefulSetAnnotation(ctx, cluster.Namespace, workersName, hash); err != nil {
		if !apierrors.IsNotFound(err) {
			return fmt.Errorf("failed to update manager-workers annotation: %w", err)
		}
		// Worker StatefulSet might not exist, ignore not-found
	}

	return nil
}

// updateDeploymentAnnotation updates the credentials hash annotation on a deployment's
// pod template to trigger a rolling restart when credentials change.
func (c *CredentialManager) updateDeploymentAnnotation(ctx context.Context, namespace, name, hash string) error {
	key := types.NamespacedName{Name: name, Namespace: namespace}

	var deployment appsv1.Deployment
	if err := c.k8sClient.Get(ctx, key, &deployment); err != nil {
		return err
	}

	if deployment.Spec.Template.Annotations == nil {
		deployment.Spec.Template.Annotations = make(map[string]string)
	}
	deployment.Spec.Template.Annotations[GetCredentialsHashAnnotationKey()] = hash

	return c.k8sClient.Update(ctx, &deployment)
}

// updateStatefulSetAnnotation updates the credentials hash annotation on a statefulset's
// pod template to trigger a rolling restart when credentials change.
func (c *CredentialManager) updateStatefulSetAnnotation(ctx context.Context, namespace, name, hash string) error {
	key := types.NamespacedName{Name: name, Namespace: namespace}

	var sts appsv1.StatefulSet
	if err := c.k8sClient.Get(ctx, key, &sts); err != nil {
		return err
	}

	if sts.Spec.Template.Annotations == nil {
		sts.Spec.Template.Annotations = make(map[string]string)
	}
	sts.Spec.Template.Annotations[GetCredentialsHashAnnotationKey()] = hash

	return c.k8sClient.Update(ctx, &sts)
}

// GetCredentialsHashAnnotationKey returns the annotation key for credentials hash
func GetCredentialsHashAnnotationKey() string {
	return "wazuh.com/credentials-hash"
}
